default:
  # Use the node image from the cistec registry as the default image for all jobs
  image: ubuntu:kinetic

stages:
  - build-apollo-router

build-apollo-router:
  image: registry.cistec.com/buildah:v1.29.1-v1
  stage: build-apollo-router
  script:
    - export COMMIT_SHA="ipv-fix"
    - export RELEASE="ipv-fix"
    - export BRANCH_NAME="ipv-fix"
    - export BUILD_TYPE="publish"
    - export DOCKER_TAG="ipv-fix"
    - export PKG_PATH="${PWD}/packages/libraries/router"
    - export CONFIG_PATH="${PWD}/configs/cargo"
    - export RUST_LOG=warn
    # - export DOCKER_REGISTRY="registry.cistec.com/"
    # Login to the gitlab registry. The --password-stdin flag is used to prevent the password from being displayed in the logs
    - echo $CI_REGISTRY_PASSWORD | buildah login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - buildah build --log-level warn --build-context pkg=${PKG_PATH} --build-context
      config=${CONFIG_PATH} --build-arg RELEASE=${RELEASE} -t
      ${CI_REGISTRY_IMAGE}/apollo-router:${DOCKER_TAG} -f ./docker/router.dockerfile .
    # Push the image to the gitlab registry
    - buildah push ${CI_REGISTRY_IMAGE}/apollo-router:${DOCKER_TAG}
