default:
  # Use the node image from the cistec registry as the default image for all jobs
  image: ubuntu:23.10

stages:
  - build-for-publish

build-for-publish:
  stage: build-for-publish
  variables:
    # TODO: use actual commit sha
    COMMIT_SHA: ipv-fix
    RELEASE: ipv-fix
    BRANCH_NAME: ipv-fix
    BUILD_TYPE: publish
    DOCKER_TAG: :ipv-fix
    DOCKER_REGISTRY: registry.cistec.com
  script:
    - export COMMIT_SHA="ipv-fix"
    - export RELEASE="ipv-fix"
    - export BRANCH_NAME="ipv-fix"
    - export BUILD_TYPE="publish"
    - export DOCKER_TAG=":ipv-fix"
    - export DOCKER_REGISTRY="registry.cistec.com/"
    - apt-get update
    - apt-get install -y rustc
    - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin
      docker-compose-plugin
    - apt-get install -y node
    - rustc -V
    - docker -v
    - node -v
    - npm i -g pnpm
    - pnpm i
    - pnpm graphql:generate
    - docker buildx bake -f docker/docker.hcl publish --load
